auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
  registry.cn-shenzhen.aliyuncs.com:
    username: ALIYUN_USERNAME
    password: ALIYUN_PASSWORD
images:
  k8s.gcr.io/sig-storage/csi-attacher: willdockerhub/csi-attacher
  k8s.gcr.io/sig-storage/csi-node-driver-registrar: willdockerhub/csi-node-driver-registrar
  k8s.gcr.io/sig-storage/csi-provisioner: willdockerhub/csi-provisioner
  k8s.gcr.io/sig-storage/csi-resizer:v1.4.0: willdockerhub/csi-resizer
  k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1: willdockerhub/csi-snapshotter
  quay.io/ceph/ceph: willdockerhub/ceph
  quay.io/cephcsi/cephcsi: willdockerhub/cephcsi
  quay.io/csiaddons/k8s-sidecar: willdockerhub/k8s-sidecar
  quay.io/csiaddons/volumereplication-operator: willdockerhub/volumereplication-operator
  rook/ceph:v1.8.6: willdockerhub/rook.ceph
