auth:
  registry.cn-shenzhen.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
  docker.io/neuvector/controller:5.0.0-b1
  docker.io/neuvector/enforcer:5.0.0-b1
  docker.io/neuvector/manager:5.0.0-b1
  docker.io/neuvector/scanner:latest
