auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
  registry.cn-beijing.aliyuncs.com:
    username: ALIYUN_USERNAME
    password: ALIYUN_PASSWORD
images:
  k8s.gcr.io/sig-storage/csi-attacher: registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-attacher
  k8s.gcr.io/sig-storage/csi-node-driver-registrar: registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-node-driver-registrar
  k8s.gcr.io/sig-storage/csi-provisioner: registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-provisioner
  k8s.gcr.io/sig-storage/csi-resizer:v1.4.0: registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-resizer
  k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1: registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-snapshotter
  quay.io/ceph/ceph: registry.cn-shenzhen.aliyuncs.com/images_mirror/ceph
  quay.io/cephcsi/cephcsi: registry.cn-shenzhen.aliyuncs.com/images_mirror/cephcsi
  quay.io/csiaddons/k8s-sidecar: registry.cn-shenzhen.aliyuncs.com/images_mirror/k8s-sidecar
  quay.io/csiaddons/volumereplication-operator: registry.cn-shenzhen.aliyuncs.com/images_mirror/volumereplication-operator
  rook/ceph:v1.8.6: registry.cn-shenzhen.aliyuncs.com/images_mirror/rook.ceph
