auth:
  registry.hub.docker.com:
    username: USERNAME
    password: PASSWORD
images:
  registry.cn-beijing.aliyuncs.com/kubesphereio/ks-jenkins:v3.2.0-2.249.1: willdockerhub/ks-jenkins:v3.2.0-2.249.1
  
  
  
