auth:
  registry.cn-shenzhen.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
# test
images:
   k8s.gcr.io/metrics-server/metrics-server: registry.cn-shenzhen.aliyuncs.com/os_mirror/metrics-server
