docker pull ccr.ccs.tencentyun.com/cube-studio/hadoop:20240501 &
docker pull ccr.ccs.tencentyun.com/cube-studio/rf-regression:20231129 &
docker pull ccr.ccs.tencentyun.com/cube-studio/lr:20230429 &
docker pull busybox:1.36.0 &
docker pull bitnami/kube-rbac-proxy:0.14.1 &
docker pull ccr.ccs.tencentyun.com/cube-studio/python:3.9 &
docker pull alpine:3.10 &
docker pull ccr.ccs.tencentyun.com/cube-studio/mindspore:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/hyperparam_search:20230530 &
docker pull carlosedp/addon-resizer:v1.8.4 &
docker pull ccr.ccs.tencentyun.com/cube-studio/nni:20240501 &
docker pull ubuntu:20.04 &
docker pull ccr.ccs.tencentyun.com/cube-studio/hyperparam_search:nni-20230530 &
docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.25.16 &
docker pull ccr.ccs.tencentyun.com/cube-studio/xgb:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook-enterprise:jupyter-ubuntu-deeplearning &
docker pull ccr.ccs.tencentyun.com/cube-studio/llama-factory:20250601 &
docker pull ccr.ccs.tencentyun.com/cube-studio/tfserving:2.3.4 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook-enterprise:matlab-ubuntu-deeplearning &
docker pull kubernetesui/dashboard:v2.6.1 &
docker pull ccr.ccs.tencentyun.com/cube-studio/deploy-service:20240601 &
docker pull projecthami/hami:v2.3.13 &
docker pull ccr.ccs.tencentyun.com/cube-studio/ubuntu-gpu:cuda11.8.0-cudnn8-python3.9 &
docker pull volcanosh/vc-webhook-manager:v1.7.0 &
docker pull argoproj/argocli:v3.4.3 &
docker pull ccr.ccs.tencentyun.com/cube-studio/label-studio:1.13.2 &
docker pull ccr.ccs.tencentyun.com/cube-studio/video-audio:20210601 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook-enterprise:jupyter-ubuntu-machinelearning &
docker pull ccr.ccs.tencentyun.com/cube-studio/offline-predict:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook-enterprise:rstudio-ubuntu-bigdata &
docker pull ccr.ccs.tencentyun.com/cube-studio/aihub:sd-webui &
docker pull argoproj/argoexec:v3.4.3 &
docker pull volcanosh/vc-controller-manager:v1.7.0 &
docker pull ccr.ccs.tencentyun.com/cube-studio/feature-process-all:20231128 &
docker pull prom/node-exporter:v1.5.0 &
docker pull ccr.ccs.tencentyun.com/cube-studio/prometheus-adapter:v0.9.1 &
docker pull ccr.ccs.tencentyun.com/cube-studio/wait-pod:v1 &
docker pull ccr.ccs.tencentyun.com/cube-studio/yolov8:2025.06 &
docker pull ccr.ccs.tencentyun.com/cube-studio/bayesian:20231222 &
docker pull ccr.ccs.tencentyun.com/cube-studio/model_evaluation:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/aihub:stable-diffusion-v3 &
docker pull ccr.ccs.tencentyun.com/cube-studio/data-process:20230501 &
docker pull ccr.ccs.tencentyun.com/cube-studio/model_register:20230501 &
docker pull ccr.ccs.tencentyun.com/cube-studio/megatron:20240101 &
docker pull ccr.ccs.tencentyun.com/cube-studio/ubuntu-gpu:cuda11.8.0-cudnn8-python3.9-dev &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook-enterprise:jupyter-ubuntu-cpu-conda &
docker pull ccr.ccs.tencentyun.com/cube-studio/union-join-data:20231129 &
docker pull ccr.ccs.tencentyun.com/cube-studio/k8s-dashboard:v2.6.1 &
docker pull prom/prometheus:v2.27.1 &
docker pull ccr.ccs.tencentyun.com/cube-studio/ar:20231128 &
docker pull docker.io/jettech/kube-webhook-certgen:v1.5.2 &
docker pull ccr.ccs.tencentyun.com/cube-studio/kubeflow-dashboard-enterprise:2025.09.01 &
docker pull kubernetesui/metrics-scraper:v1.0.8 &
docker pull ccr.ccs.tencentyun.com/cube-studio/feature-process:20230501 &
docker pull postgres:11.5 &
docker pull ccr.ccs.tencentyun.com/cube-studio/feature-importance:20231129 &
docker pull istio/proxyv2:1.15.0 &
docker pull istio/pilot:1.15.0 &
docker pull grafana/grafana:9.5.20 &
docker pull ccr.ccs.tencentyun.com/cube-studio/neo4j:4.4 &
docker pull ccr.ccs.tencentyun.com/cube-studio/nlp-process:20240601 &
docker pull ccr.ccs.tencentyun.com/cube-studio/tritonserver:22.07-py3 &
docker pull ccr.ccs.tencentyun.com/cube-studio/ray-sklearn:20240101 &
docker pull ccr.ccs.tencentyun.com/cube-studio/aihub:vllm &
docker pull vllm/vllm-openai:v0.8.5.post1
docker pull ccr.ccs.tencentyun.com/cube-studio/tf:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/ml-server:20240601 &
docker pull kubeflow/training-operator:v1-8a066f9 &
docker pull docker:23.0.4 &
docker pull nvidia/k8s-device-plugin:v0.11.0-ubuntu20.04 &
docker pull ccr.ccs.tencentyun.com/cube-studio/spark:20230701 &
docker pull ccr.ccs.tencentyun.com/cube-studio/baichuan2:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/horovod:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/feature-combine:20231129 &
docker pull ccr.ccs.tencentyun.com/cube-studio/llm-server:20240601 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook-enterprise:jupyter-ubuntu-bigdata &
docker pull ccr.ccs.tencentyun.com/cube-studio/modelscope:base-cuda11.3-python3.7 &
docker pull ccr.ccs.tencentyun.com/cube-studio/hadamard-multiply:20231129 &
docker pull bitnami/redis:7.4 &
docker pull python:3.9 &
docker pull ccr.ccs.tencentyun.com/cube-studio/model_download:20240501 &
docker pull ccr.ccs.tencentyun.com/cube-studio/gbdt:20230429 &
docker pull ccr.ccs.tencentyun.com/cube-studio/pytorch:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/deepspeed:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/modelscope:baichuan2 &
docker pull volcanosh/vc-scheduler:v1.7.0 &
docker pull minio/minio:RELEASE.2023-04-20T17-56-55Z &
docker pull ccr.ccs.tencentyun.com/cube-studio/llama2:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/dataset:20240501 &
docker pull ccr.ccs.tencentyun.com/cube-studio/chatglm:20240301 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook-enterprise:jupyter-ubuntu-gpu-conda &
docker pull ccr.ccs.tencentyun.com/cube-studio/kubeflow-dashboard-frontend-enterprise:2025.09.01 &
docker pull ccr.ccs.tencentyun.com/cube-studio/adaboost:20230505 &
docker pull ccr.ccs.tencentyun.com/cube-studio/kmeans:20230506 &
docker pull ccr.ccs.tencentyun.com/cube-studio/knn:20230529 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook-enterprise:vscode-ubuntu-cpu-conda &
docker pull mpioperator/kubectl-delivery:latest &
docker pull ccr.ccs.tencentyun.com/cube-studio/model-convert:20230601 &
docker pull ccr.ccs.tencentyun.com/cube-studio/modelscope:base-cuda11.8-python3.8 &
docker pull ccr.ccs.tencentyun.com/cube-studio/arima:20231129 &
docker pull ccr.ccs.tencentyun.com/cube-studio/datax:20240501 &
docker pull ccr.ccs.tencentyun.com/cube-studio/torchserve:0.7.1-cpu &
docker pull ccr.ccs.tencentyun.com/cube-studio/modelscope:base-cuda12.1-python3.10 &
docker pull ccr.ccs.tencentyun.com/cube-studio/aihub:stable-diffusion &
docker pull ccr.ccs.tencentyun.com/cube-studio/patrikx3:latest &
docker pull ccr.ccs.tencentyun.com/cube-studio/volcano:20230601 &
docker pull ccr.ccs.tencentyun.com/cube-studio/randomforest:20230427 &
docker pull quay.io/prometheus-operator/prometheus-operator:v0.46.0 &
docker pull argoproj/workflow-controller:v3.4.3 &
docker pull ccr.ccs.tencentyun.com/cube-studio/lightgbm:20230428 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook-enterprise:jupyter-ubuntu-cpu-pro &
docker pull ccr.ccs.tencentyun.com/cube-studio/deepspeed:cuda-11.7.1-openmpi-4.0-python3.6-tf1.15-pytorch1.9-deepspeed-0.10.1 &
docker pull nvidia/dcgm-exporter:3.1.7-3.1.4-ubuntu20.04 &
docker pull quay.io/prometheus-operator/prometheus-config-reloader:v0.46.0 &
docker pull ccr.ccs.tencentyun.com/cube-studio/paddle:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/hyperparam_search:nni-20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook-enterprise:vscode-ubuntu-gpu-conda &
docker pull ccr.ccs.tencentyun.com/cube-studio/colossalai:20230801 &
docker pull phpmyadmin:5.2.1 &
docker pull mysql:8.0.32 &
docker pull ccr.ccs.tencentyun.com/cube-studio/mxnet:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/ray:gpu-20240101 &
docker pull ccr.ccs.tencentyun.com/cube-studio/decision-tree:20250301 &
docker pull ccr.ccs.tencentyun.com/cube-studio/mpi:20230801 &

wait
