# This is a basic workflow to help you get started with Actions

name: image-sync
on:
  push:
    branches: [ cube-studio ]

env:
  IMAGE_SYNCER_VERSION: v1.5.4

jobs:
  image-sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install image-sync tool
      run: |
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/${IMAGE_SYNCER_VERSION}/image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
        tar -zxf image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
        
        
    - name: Synchronization
      env:
        AUTH: ${{ secrets.AUTH }}
      if: github.event_name == 'push'
      run: echo "$AUTH" > ./auth.yaml && .github/workflows/sync.sh