# This is a basic workflow to help you get started with Actions

name: image-sync
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_SYNCER_VERSION: v1.3.0

jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install image-sync tool
      run: |
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/${IMAGE_SYNCER_VERSION}/image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
        tar -zxf image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz

    - name: init config.yaml with env
      run: |
        curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst && chmod +x ./envsubst
        ./envsubst < config.yaml.tmpl > config.yaml
        cat config.yaml

    - name: sync images
      run: |
        ./image-syncer --proc=20 --config=config.yaml --retries=3
