name: metrics-server

on: push

env:
  DOCKERHUB_USERNAME: willdockerhub

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk:alpine

    steps:
      - uses: actions/checkout@v1
      - name: glcoud auth
        run: |
          echo $GCLOUD_SDK_JSON > gcloud_sdk.json
